(cl:in-package epoc-msg)
(cl:export '(HEADER-VAL
          HEADER
          SEN1-VAL
          SEN1
          SEN2-VAL
          SEN2
          SEN3-VAL
          SEN3
          SEN4-VAL
          SEN4
          SEN5-VAL
          SEN5
          SEN6-VAL
          SEN6
          SEN7-VAL
          SEN7
          SEN8-VAL
          SEN8
          SEN9-VAL
          SEN9
          SEN10-VAL
          SEN10
          SEN11-VAL
          SEN11
          SEN12-VAL
          SEN12
          SEN13-VAL
          SEN13
          SEN14-VAL
          SEN14
))